import { Platform } from 'react-native';

const light = {
  background: '#FFFFFF',
  backgroundSecondary: '#F8F7FF',
  surface: '#FFFFFF',
  text: '#1A1A2E',
  textSecondary: '#6B7280',
  textTertiary: '#9CA3AF',
  textInverse: '#FFFFFF',
  primary: '#7C3AED',
  primarySoft: '#EDE9FE',
  cardMint: '#D1FAE5',
  cardMintText: '#065F46',
  cardLavender: '#EDE9FE',
  cardLavenderText: '#4C1D95',
  cardPeach: '#FEE2E2',
  cardPeachText: '#7F1D1D',
  cardYellow: '#FEF9C3',
  cardYellowText: '#713F12',
  cardSky: '#DBEAFE',
  cardSkyText: '#1E3A8A',
  cardPink: '#FCE7F3',
  cardPinkText: '#831843',
  border: '#E5E7EB',
  borderLight: '#F3F4F6',
  shadow: '#1A1A2E',
  success: '#10B981',
  successSoft: '#D1FAE5',
  warning: '#F59E0B',
  warningSoft: '#FEF3C7',
  error: '#EF4444',
  errorSoft: '#FEE2E2',
  tabBar: '#1A1A2E',
  tabBarActive: '#7C3AED',
  tabBarInactive: '#6B7280',
  tabBarActiveBg: '#EDE9FE',
  card: '#FFFFFF',
  mutedText: '#6B7280',
  subtleText: '#9CA3AF',
  onPrimary: '#FFFFFF',
  danger: '#EF4444',
  tint: '#7C3AED',
  icon: '#6B7280',
  tabIconDefault: '#6B7280',
  tabIconSelected: '#7C3AED',
  welcomeSoft: '#F8F7FF',
  engineering: '#7C3AED',
  engineeringSoft: '#EDE9FE',
  health: '#0D9488',
  healthSoft: '#DBEAFE',
};

const dark = {
  background: '#0F0F1A',
  backgroundSecondary: '#1A1A2E',
  surface: '#1E1E30',
  text: '#F9FAFB',
  textSecondary: '#D1D5DB',
  textTertiary: '#6B7280',
  textInverse: '#1A1A2E',
  primary: '#A78BFA',
  primarySoft: '#2D1B69',
  cardMint: '#064E3B',
  cardMintText: '#6EE7B7',
  cardLavender: '#2D1B69',
  cardLavenderText: '#C4B5FD',
  cardPeach: '#7F1D1D',
  cardPeachText: '#FCA5A5',
  cardYellow: '#713F12',
  cardYellowText: '#FDE68A',
  cardSky: '#1E3A8A',
  cardSkyText: '#93C5FD',
  cardPink: '#831843',
  cardPinkText: '#F9A8D4',
  border: '#374151',
  borderLight: '#1F2937',
  shadow: '#000000',
  success: '#10B981',
  successSoft: '#064E3B',
  warning: '#F59E0B',
  warningSoft: '#451A03',
  error: '#EF4444',
  errorSoft: '#7F1D1D',
  tabBar: '#0F0F1A',
  tabBarActive: '#A78BFA',
  tabBarInactive: '#4B5563',
  tabBarActiveBg: '#2D1B69',
  card: '#1E1E30',
  mutedText: '#D1D5DB',
  subtleText: '#6B7280',
  onPrimary: '#1A1A2E',
  danger: '#EF4444',
  tint: '#A78BFA',
  icon: '#D1D5DB',
  tabIconDefault: '#4B5563',
  tabIconSelected: '#A78BFA',
  welcomeSoft: '#1A1A2E',
  engineering: '#A78BFA',
  engineeringSoft: '#2D1B69',
  health: '#2DD4BF',
  healthSoft: '#1E3A8A',
};

export const Colors = {
  light,
  dark,
};

export const Fonts = Platform.select({
  ios: {
    sans: 'system-ui',
    serif: 'ui-serif',
    rounded: 'ui-rounded',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
